"""ondelete

Revision ID: 9b796129af51
Revises: 6c512b9b8f5b
Create Date: 2024-08-09 15:27:16.760517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b796129af51'
down_revision: Union[str, None] = '6c512b9b8f5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'task', ['id'])
    op.drop_constraint('task_permissions_task_id_fkey', 'task_permissions', type_='foreignkey')
    op.drop_constraint('task_permissions_user_id_fkey', 'task_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'task_permissions', 'task', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task_permissions', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'task_permissions', type_='foreignkey')
    op.drop_constraint(None, 'task_permissions', type_='foreignkey')
    op.create_foreign_key('task_permissions_user_id_fkey', 'task_permissions', 'user', ['user_id'], ['id'])
    op.create_foreign_key('task_permissions_task_id_fkey', 'task_permissions', 'task', ['task_id'], ['id'])
    op.drop_constraint(None, 'task', type_='unique')
    # ### end Alembic commands ###
