"""rename to login

Revision ID: 527454875da7
Revises: 9b796129af51
Create Date: 2024-08-09 16:18:12.379997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '527454875da7'
down_revision: Union[str, None] = '9b796129af51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_permissions', sa.Column('user_login', sa.String(), nullable=True))
    op.drop_constraint('task_permissions_user_id_fkey', 'task_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'task_permissions', 'user', ['user_login'], ['login'], ondelete='CASCADE')
    op.drop_column('task_permissions', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_permissions', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task_permissions', type_='foreignkey')
    op.create_foreign_key('task_permissions_user_id_fkey', 'task_permissions', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('task_permissions', 'user_login')
    # ### end Alembic commands ###
